Deploy to subfolder
mong/qmongjs pull request #571
Opened 2021-05-31 10:04 UTC by LarsJK

Fant ut at den enkleste måten å route til riktig app er å deploye denne til /kvalitestregistre i samme s3 bucket.

Da trengte jeg ikke endre noe i AWS oppsettet med cloudfront

2021-05-31 11:33 UTC, arnfinn requested changes
Lokalt så fikk jeg ikke sti til å fungere for "Velg register". Dvs. sti til registersidene fungerte ikke (f.eks hvis jeg velger Hjerteinfarkt sendes jeg til http://localhost:3000/kvalitetsregistre/kvalitetsregistre/hjerteinfarkt, som returnerer *Page Not Found*)

2021-06-01 08:13 UTC, LarsJK commented
@arnfinn Da skal routingen være fikset.

La merke til at sidebar blir borte når man har valgt ett register, men ser det er sånn i master også så jeg lot det være.

2021-06-01 10:08 UTC, arnfinn commented on src/components/RegisterPage/index.tsx
> +        <Route exact path={`/r/:register`}>
Vil det fungere uten `r/` her?

2021-06-01 10:09 UTC, arnfinn commented on src/components/SelectRegister/index.tsx
> +              <Link to={`/r/${reg.registerShortName}`}>
Vil det fungere uten `r/`?

2021-06-01 10:10 UTC, arnfinn commented
Det er meningen at sidebar skal forsvinne når man går inn på et register. Fra egne register-sider skal man kunne lenke direkte til disse sidene.

2021-06-01 10:27 UTC, yte0 approved these changes

2021-06-01 12:24 UTC, LarsJK commented on src/components/RegisterPage/index.tsx
> +        <Route exact path={`/r/:register`}>
Ja det fungerer men du får en liten render flash før den går til 404 om du går til en url som ikke finnes

`/eksisterer-ikke` matcher /:register så failer SelectedRegister siden register=eksisterer-ikke ikke finnes

2021-06-02 11:29 UTC, arnfinn approved these changes

2021-06-02 11:34 UTC, arnfinn commented
Hvis jeg går direkte til et register, med lenke, så havner jeg på forsiden (f.eks https://qa.skde.org/kvalitetsregistre/leddprotese). Er dette enkelt å fikse?

2021-06-04 11:22 UTC, LarsJK commented
@arnfinn Prøvde endel forskjellig her. Blant annet testet jeg å bruke s3 redirect rules, sette opp flere cloudfront origins + behaviours, og lambda@edge, men det eneste jeg fikk til å fungere bra nok var å redirecte 404 til qmongjs (/kvalitetsregistre/index.html)

<img width="1320" alt="Skjermbilde 2021-06-04 kl  13 16 33" src="https://user-images.githubusercontent.com/1528255/120793499-3fd92280-c537-11eb-9c3f-515f9f4bb5a5.png">

Tror det fungerer godt nok dere kan teste qa.skde.org litt nå.

Alternativt så tror jeg man må se på å hoste dette på en liten ec2 instans med apache/nginx og rewrite rules til riktig app. Det kunne også vært aktuelt å bake qmongjs inn i qmongts istedet kanskje.

2021-06-04 11:45 UTC, arnfinn commented
@LarsJK Det ser ut til å fungere fint nå!

2021-06-07 08:41 UTC, merged